/* The following code was generated by JFlex 1.6.1 */

/*----------------- AREA 1: CODIGO DE USUARIO -----------------------*/
//-----------------> paquetes, importaciones 
package Analizadores;
import java_cup.runtime.*;
import javax.swing.table.DefaultTableModel;

/*----------------- AREA 2: OPCIONES Y DECLARACIONES -----------------------*/


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>A_Lexico.jflex</tt>
 */
public class Analizador_Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\2\1\55\1\5\1\6\22\0\1\5\1\27\1\11"+
    "\5\0\1\17\1\20\1\3\1\0\1\21\1\24\1\23\1\1\12\4"+
    "\1\0\1\22\1\26\1\12\1\25\2\0\1\32\1\53\1\30\1\52"+
    "\1\34\1\54\1\40\1\45\1\42\2\7\1\31\1\46\1\50\1\44"+
    "\1\47\1\7\1\37\1\36\1\43\1\51\1\33\4\7\1\13\1\0"+
    "\1\14\1\0\1\10\1\0\1\32\1\53\1\30\1\52\1\34\1\54"+
    "\1\40\1\45\1\42\2\7\1\31\1\46\1\50\1\44\1\47\1\7"+
    "\1\37\1\36\1\43\1\51\1\33\4\7\1\15\1\0\1\16\7\0"+
    "\1\55\252\0\2\41\115\0\1\35\u1ea8\0\1\55\1\55\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\1\3\4\1\1\3\4\1\1"+
    "\4\4\3\0\1\22\1\23\1\24\1\25\1\26\5\4"+
    "\1\0\3\4\1\0\4\4\1\27\2\0\5\4\1\0"+
    "\3\4\1\0\4\4\2\0\5\4\1\0\1\4\1\0"+
    "\2\4\1\0\4\4\1\27\4\4\1\0\1\4\2\30"+
    "\1\0\1\4\1\0\1\4\1\0\4\4\2\31\1\32"+
    "\1\33\1\4\1\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\3\4\1\0\1\4\1\0\2\4\2\34\1\0"+
    "\1\4\1\0\1\4\1\0\2\4\1\0\1\4\1\0"+
    "\1\4\2\35\1\4\1\0\1\4\2\36\2\37\1\0"+
    "\1\4\2\40\2\41\1\0\1\4\2\42\2\43\1\0"+
    "\1\4\2\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\56\0\212\0\270\0\346\0\u0114"+
    "\0\56\0\56\0\56\0\56\0\56\0\56\0\56\0\56"+
    "\0\56\0\56\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228"+
    "\0\u0256\0\u0284\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398"+
    "\0\u03c6\0\u03f4\0\u0422\0\346\0\56\0\56\0\56\0\56"+
    "\0\56\0\u0450\0\u047e\0\u04ac\0\u04da\0\u0508\0\u0536\0\u0564"+
    "\0\u0592\0\u05c0\0\u05ee\0\u061c\0\u064a\0\u0678\0\u06a6\0\u03f4"+
    "\0\u06d4\0\u0702\0\u0730\0\u075e\0\u078c\0\u07ba\0\u07e8\0\u0816"+
    "\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958\0\u0986"+
    "\0\u09b4\0\u09e2\0\u0a10\0\u0a3e\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6"+
    "\0\u0b24\0\u0b52\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66"+
    "\0\u0c94\0\56\0\u0cc2\0\u0cf0\0\u0d1e\0\u0d4c\0\u0d7a\0\u0da8"+
    "\0\56\0\270\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\u0e8e\0\u0ebc"+
    "\0\u0eea\0\u0f18\0\u0f46\0\56\0\270\0\270\0\u0f74\0\u0fa2"+
    "\0\u0fd0\0\u0ffe\0\u102c\0\u105a\0\u1088\0\u10b6\0\u10e4\0\u1112"+
    "\0\u1140\0\u116e\0\u119c\0\u11ca\0\u11f8\0\u1226\0\u1254\0\56"+
    "\0\270\0\u1282\0\u12b0\0\u12de\0\u130c\0\u133a\0\u1368\0\u1396"+
    "\0\u13c4\0\u13f2\0\u1420\0\u144e\0\56\0\270\0\u147c\0\u14aa"+
    "\0\u14d8\0\56\0\270\0\56\0\270\0\u1506\0\u1534\0\56"+
    "\0\270\0\56\0\270\0\u1562\0\u1590\0\56\0\270\0\56"+
    "\0\270\0\u15be\0\u15ec\0\56\0\270";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\2\4\1\6\1\2"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\2\6\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\6\1\37\2\6\1\40\1\41\4\6\60\0"+
    "\1\42\1\0\1\43\56\0\1\5\55\0\1\6\2\0"+
    "\2\6\17\0\5\6\1\0\3\6\1\0\13\6\1\0"+
    "\2\44\1\45\6\44\1\45\44\44\12\0\1\46\55\0"+
    "\1\47\55\0\1\50\55\0\1\51\47\0\1\6\2\0"+
    "\2\6\17\0\1\6\1\52\1\53\2\6\1\0\3\6"+
    "\1\0\2\6\1\54\10\6\5\0\1\6\2\0\2\6"+
    "\17\0\4\6\1\55\1\0\3\6\1\0\13\6\5\0"+
    "\1\6\2\0\2\6\17\0\5\6\1\0\1\6\1\56"+
    "\1\6\1\0\13\6\52\0\1\57\10\0\1\6\2\0"+
    "\2\6\17\0\5\6\1\0\3\6\1\0\7\6\1\60"+
    "\3\6\5\0\1\6\2\0\2\6\17\0\4\6\1\61"+
    "\1\0\3\6\1\0\13\6\5\0\1\6\2\0\2\6"+
    "\17\0\5\6\1\0\1\6\1\62\1\6\1\0\13\6"+
    "\47\0\1\63\13\0\1\6\2\0\2\6\17\0\5\6"+
    "\1\0\3\6\1\0\4\6\1\64\6\6\5\0\1\6"+
    "\2\0\2\6\17\0\5\6\1\0\3\6\1\0\11\6"+
    "\1\65\1\6\5\0\1\6\2\0\2\6\17\0\5\6"+
    "\1\0\1\6\1\66\1\6\1\0\13\6\5\0\1\6"+
    "\2\0\2\6\17\0\5\6\1\0\3\6\1\0\7\6"+
    "\1\67\3\6\1\0\2\70\1\0\3\70\1\0\47\70"+
    "\1\71\1\72\54\71\4\0\1\6\2\0\2\6\17\0"+
    "\2\6\1\73\2\6\1\0\3\6\1\0\13\6\5\0"+
    "\1\6\2\0\2\6\17\0\5\6\1\0\3\6\1\0"+
    "\10\6\1\74\2\6\5\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\0\3\6\1\0\6\6\1\75\4\6\5\0"+
    "\1\6\2\0\2\6\17\0\4\6\1\76\1\0\3\6"+
    "\1\0\13\6\5\0\1\6\2\0\2\6\17\0\1\77"+
    "\4\6\1\0\3\6\1\0\13\6\47\0\1\100\13\0"+
    "\1\6\2\0\2\6\17\0\5\6\1\0\3\6\1\0"+
    "\4\6\1\101\6\6\5\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\0\2\6\1\102\1\0\13\6\5\0\1\6"+
    "\2\0\2\6\17\0\2\6\1\103\2\6\1\0\3\6"+
    "\1\0\13\6\50\0\1\104\12\0\1\6\2\0\2\6"+
    "\17\0\5\6\1\0\3\6\1\0\5\6\1\105\5\6"+
    "\5\0\1\6\2\0\2\6\17\0\5\6\1\0\3\6"+
    "\1\0\1\6\1\106\11\6\5\0\1\6\2\0\2\6"+
    "\17\0\5\6\1\0\3\6\1\0\2\6\1\107\10\6"+
    "\5\0\1\6\2\0\2\6\17\0\5\6\1\0\3\6"+
    "\1\0\4\6\1\110\6\6\1\0\3\71\1\111\52\71"+
    "\1\0\1\72\1\0\1\112\56\0\1\6\2\0\2\6"+
    "\17\0\3\6\1\113\1\6\1\0\3\6\1\0\13\6"+
    "\5\0\1\6\2\0\2\6\17\0\4\6\1\114\1\0"+
    "\3\6\1\0\13\6\5\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\0\3\6\1\0\1\6\1\115\11\6\5\0"+
    "\1\6\2\0\2\6\17\0\5\6\1\0\1\6\1\116"+
    "\1\6\1\0\13\6\5\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\0\3\6\1\0\3\6\1\117\7\6\33\0"+
    "\1\120\27\0\1\6\2\0\2\6\17\0\2\6\1\121"+
    "\2\6\1\0\3\6\1\0\13\6\5\0\1\6\2\0"+
    "\2\6\17\0\5\6\1\0\3\6\1\122\1\123\12\6"+
    "\5\0\1\6\2\0\2\6\17\0\5\6\1\0\3\6"+
    "\1\0\12\6\1\124\40\0\1\125\22\0\1\6\2\0"+
    "\2\6\17\0\5\6\1\0\1\6\1\126\1\6\1\0"+
    "\13\6\5\0\1\6\2\0\2\6\17\0\4\6\1\127"+
    "\1\0\3\6\1\0\13\6\5\0\1\6\2\0\2\6"+
    "\17\0\5\6\1\0\3\6\1\0\4\6\1\130\6\6"+
    "\5\0\1\6\2\0\2\6\17\0\4\6\1\131\1\0"+
    "\3\6\1\0\13\6\1\0\1\71\1\132\1\71\1\111"+
    "\52\71\1\0\1\132\60\0\1\6\2\0\2\6\17\0"+
    "\4\6\1\133\1\0\3\6\1\0\13\6\5\0\1\6"+
    "\2\0\2\6\17\0\5\6\1\0\3\6\1\0\6\6"+
    "\1\134\4\6\5\0\1\6\2\0\2\6\17\0\2\6"+
    "\1\135\2\6\1\0\3\6\1\0\13\6\5\0\1\6"+
    "\2\0\2\6\17\0\2\6\1\136\2\6\1\0\3\6"+
    "\1\0\13\6\5\0\1\6\2\0\2\6\17\0\5\6"+
    "\1\0\3\6\1\137\1\140\12\6\40\0\1\141\22\0"+
    "\1\6\2\0\2\6\17\0\5\6\1\0\1\6\1\142"+
    "\1\6\1\0\13\6\36\0\2\143\23\0\1\6\2\0"+
    "\2\6\17\0\5\6\1\143\1\144\2\6\1\0\13\6"+
    "\5\0\1\6\2\0\2\6\17\0\5\6\1\0\3\6"+
    "\1\145\1\146\12\6\42\0\2\147\17\0\1\6\2\0"+
    "\2\6\17\0\5\6\1\0\3\6\1\147\1\150\12\6"+
    "\5\0\1\6\2\0\2\6\17\0\5\6\1\0\3\6"+
    "\1\0\6\6\1\151\4\6\5\0\1\6\2\0\2\6"+
    "\17\0\4\6\1\152\1\0\3\6\1\0\13\6\5\0"+
    "\1\6\2\0\2\6\17\0\5\6\1\0\1\6\1\153"+
    "\1\6\1\0\13\6\5\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\154\1\155\2\6\1\0\13\6\5\0\1\6"+
    "\2\0\2\6\17\0\2\6\1\156\2\6\1\0\3\6"+
    "\1\0\13\6\5\0\1\6\2\0\2\6\17\0\5\6"+
    "\1\0\1\6\1\157\1\6\1\0\13\6\5\0\1\6"+
    "\2\0\2\6\17\0\5\6\1\0\1\6\1\160\1\6"+
    "\1\0\13\6\34\0\1\161\26\0\1\6\2\0\2\6"+
    "\17\0\3\6\1\162\1\6\1\0\3\6\1\0\13\6"+
    "\44\0\1\163\16\0\1\6\2\0\2\6\17\0\5\6"+
    "\1\0\3\6\1\0\1\6\1\164\11\6\31\0\1\165"+
    "\31\0\1\6\2\0\2\6\17\0\1\166\4\6\1\0"+
    "\3\6\1\0\13\6\47\0\1\167\13\0\1\6\2\0"+
    "\2\6\17\0\5\6\1\0\3\6\1\0\4\6\1\170"+
    "\6\6\5\0\1\6\2\0\2\6\17\0\4\6\1\171"+
    "\1\0\3\6\1\0\13\6\5\0\1\6\2\0\2\6"+
    "\17\0\5\6\1\0\3\6\1\0\10\6\1\172\2\6"+
    "\5\0\1\6\2\0\2\6\17\0\5\6\1\0\3\6"+
    "\1\173\1\174\12\6\5\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\175\1\176\2\6\1\0\13\6\5\0\1\6"+
    "\2\0\2\6\17\0\1\177\4\6\1\0\3\6\1\0"+
    "\13\6\45\0\1\200\15\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\0\3\6\1\0\2\6\1\201\10\6\40\0"+
    "\1\202\22\0\1\6\2\0\2\6\17\0\5\6\1\0"+
    "\1\6\1\203\1\6\1\0\13\6\33\0\1\204\27\0"+
    "\1\6\2\0\2\6\17\0\2\6\1\205\2\6\1\0"+
    "\3\6\1\0\13\6\42\0\2\206\17\0\1\6\2\0"+
    "\2\6\17\0\5\6\1\0\3\6\1\206\1\207\12\6"+
    "\5\0\1\6\2\0\2\6\17\0\5\6\1\0\1\6"+
    "\1\210\1\6\1\0\13\6\5\0\1\6\2\0\2\6"+
    "\17\0\5\6\1\0\3\6\1\211\1\212\12\6\31\0"+
    "\1\213\31\0\1\6\2\0\2\6\17\0\1\214\4\6"+
    "\1\0\3\6\1\0\13\6\42\0\2\215\17\0\1\6"+
    "\2\0\2\6\17\0\5\6\1\0\3\6\1\215\1\216"+
    "\12\6\5\0\1\6\2\0\2\6\17\0\5\6\1\0"+
    "\3\6\1\0\3\6\1\217\7\6\45\0\1\220\15\0"+
    "\1\6\2\0\2\6\17\0\5\6\1\0\3\6\1\0"+
    "\2\6\1\221\10\6\40\0\1\222\22\0\1\6\2\0"+
    "\2\6\17\0\5\6\1\0\1\6\1\223\1\6\1\0"+
    "\13\6\40\0\1\224\22\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\0\1\6\1\225\1\6\1\0\13\6\5\0"+
    "\1\6\2\0\2\6\17\0\5\6\1\226\1\227\2\6"+
    "\1\0\13\6\45\0\1\230\15\0\1\6\2\0\2\6"+
    "\17\0\5\6\1\0\3\6\1\0\2\6\1\231\10\6"+
    "\45\0\1\232\15\0\1\6\2\0\2\6\17\0\5\6"+
    "\1\0\3\6\1\0\2\6\1\233\10\6\5\0\1\6"+
    "\2\0\2\6\17\0\5\6\1\0\3\6\1\234\1\235"+
    "\12\6\36\0\2\236\23\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\236\1\237\2\6\1\0\13\6\42\0\2\240"+
    "\17\0\1\6\2\0\2\6\17\0\5\6\1\0\3\6"+
    "\1\240\1\241\12\6\34\0\1\242\26\0\1\6\2\0"+
    "\2\6\17\0\3\6\1\243\1\6\1\0\3\6\1\0"+
    "\13\6\45\0\1\244\15\0\1\6\2\0\2\6\17\0"+
    "\5\6\1\0\3\6\1\0\2\6\1\245\10\6\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5658];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\4\1\12\11\17\1\3\0"+
    "\5\11\5\1\1\0\3\1\1\0\5\1\2\0\5\1"+
    "\1\0\3\1\1\0\4\1\2\0\5\1\1\0\1\1"+
    "\1\0\2\1\1\0\4\1\1\11\4\1\1\0\1\1"+
    "\1\11\1\1\1\0\1\1\1\0\1\1\1\0\4\1"+
    "\1\11\4\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\3\1\1\0\1\1\1\0\2\1\1\11\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\2\1\1\0\1\1"+
    "\1\0\1\1\1\11\2\1\1\0\1\1\1\11\1\1"+
    "\1\11\1\1\1\0\1\1\1\11\1\1\1\11\1\1"+
    "\1\0\1\1\1\11\1\1\1\11\1\1\1\0\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //--------> Codigo de usuario en sintaxis java

    public String errores = "";
    public String lexemas = "";
    public static Object [] encabezado={"","",""};
    public static DefaultTableModel tablaerrores=new DefaultTableModel(encabezado,0);
    

    public void addError(String cadena)
    {
    	errores += "\n" + cadena;        
    }
    public void addLexema(Symbol s)
    {
        lexemas+=Simbolos.terminalNames[s.sym] +"\t"+ s.value + "\t" + s.left + "\t" + s.right +"\n";
    }
   


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador_Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 210) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { addError("Error lexico: "+yytext()+ " Linea:"+(yyline+1)+" Columna:"+(yycolumn+1));
       Object[] cars = {yytext(), (yyline+1), (yycolumn+1)};
       tablaerrores.addRow(cars);
       System.out.println("Error lexico: "+yytext()+ " Linea:"+(yyline+1)+" Columna:"+(yycolumn+1));
            }
          case 37: break;
          case 2: 
            { /*Se ignora*/
            }
          case 38: break;
          case 3: 
            { Symbol s = new  Symbol(Simbolos.enteroposit,yycolumn,yyline,Integer.parseInt(yytext())); addLexema(s); return s;
            }
          case 39: break;
          case 4: 
            { Symbol s = new  Symbol(Simbolos.id,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 40: break;
          case 5: 
            { Symbol s = new  Symbol(Simbolos.igual,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 41: break;
          case 6: 
            { Symbol s = new Symbol(Simbolos.corchabre,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 42: break;
          case 7: 
            { Symbol s = new Symbol(Simbolos.corchcierra,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 43: break;
          case 8: 
            { Symbol s = new Symbol(Simbolos.llaveabre,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 44: break;
          case 9: 
            { Symbol s = new Symbol(Simbolos.llavecierra,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 45: break;
          case 10: 
            { Symbol s = new Symbol(Simbolos.parenabre,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 46: break;
          case 11: 
            { Symbol s = new Symbol(Simbolos.parencierra,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 47: break;
          case 12: 
            { Symbol s = new Symbol(Simbolos.coma,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 48: break;
          case 13: 
            { Symbol s = new Symbol(Simbolos.puntocoma,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 49: break;
          case 14: 
            { Symbol s = new Symbol(Simbolos.punto,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 50: break;
          case 15: 
            { Symbol s = new Symbol(Simbolos.menos,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 51: break;
          case 16: 
            { Symbol s = new Symbol(Simbolos.mayor,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 52: break;
          case 17: 
            { Symbol s = new Symbol(Simbolos.menor,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 53: break;
          case 18: 
            { Symbol s = new Symbol(Simbolos.cadena,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 54: break;
          case 19: 
            { Symbol s = new Symbol(Simbolos.igualigual,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 55: break;
          case 20: 
            { Symbol s = new Symbol(Simbolos.mayorigualque,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 56: break;
          case 21: 
            { Symbol s = new Symbol(Simbolos.menorigualque,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 57: break;
          case 22: 
            { Symbol s = new Symbol(Simbolos.diferenteque,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 58: break;
          case 23: 
            { /*Se ignora.*/
            }
          case 59: break;
          case 24: 
            { Symbol s = new Symbol(Simbolos.sumar,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 60: break;
          case 25: 
            { Symbol s = new Symbol(Simbolos.claves,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 61: break;
          case 26: 
            { Symbol s = new Symbol(Simbolos.cadenareserv,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 62: break;
          case 27: 
            { Symbol s = new Symbol(Simbolos.contar,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 63: break;
          case 28: 
            { Symbol s = new Symbol(Simbolos.archivo,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 64: break;
          case 29: 
            { Symbol s = new Symbol(Simbolos.contarsi,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 65: break;
          case 30: 
            { Symbol s = new Symbol(Simbolos.graficar,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 66: break;
          case 31: 
            { Symbol s = new Symbol(Simbolos.imprimir,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 67: break;
          case 32: 
            { Symbol s = new Symbol(Simbolos.promedio,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 68: break;
          case 33: 
            { Symbol s = new Symbol(Simbolos.numerico,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 69: break;
          case 34: 
            { Symbol s = new Symbol(Simbolos.registros,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 70: break;
          case 35: 
            { Symbol s = new Symbol(Simbolos.obtenersi,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 71: break;
          case 36: 
            { Symbol s = new Symbol(Simbolos.leerarchivo,yycolumn,yyline,yytext()); addLexema(s); return s;
            }
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
