
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java_cup.runtime.Symbol;
import java.io.*;
import java.util.*;
import java.text.*;
import java.util.Stack;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class analisis_sintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolos.class;
}

  /** Default constructor. */
  @Deprecated
  public analisis_sintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public analisis_sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public analisis_sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\052\000\002\002\004\000\002\002\010\000\002\002" +
    "\010\000\002\002\010\000\002\002\013\000\002\002\015" +
    "\000\002\002\013\000\002\002\015\000\002\002\021\000" +
    "\002\002\021\000\002\002\021\000\002\002\021\000\002" +
    "\002\020\000\002\002\002\000\002\010\005\000\002\010" +
    "\005\000\002\010\003\000\002\010\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\007\003\000\002" +
    "\007\004\000\002\007\005\000\002\007\006\000\002\004" +
    "\005\000\002\004\003\000\002\005\006\000\002\005\002" +
    "\000\002\006\005\000\002\006\005\000\002\006\006\000" +
    "\002\006\007\000\002\006\010\000\002\006\005\000\002" +
    "\006\006\000\002\006\003\000\002\006\003\000\002\006" +
    "\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\223\000\022\002\ufff4\025\010\026\013\027\006\031" +
    "\012\032\004\037\007\041\005\001\002\000\004\042\156" +
    "\001\002\000\004\011\141\001\002\000\004\042\131\001" +
    "\002\000\004\042\072\001\002\000\004\004\062\001\002" +
    "\000\004\002\061\001\002\000\004\011\047\001\002\000" +
    "\004\004\014\001\002\000\004\005\015\001\002\000\006" +
    "\006\uffe2\007\016\001\002\000\010\016\024\043\023\044" +
    "\025\001\002\000\004\006\020\001\002\000\022\002\ufff4" +
    "\025\010\026\013\027\006\031\012\032\004\037\007\041" +
    "\005\001\002\000\004\002\uffff\001\002\000\004\010\045" +
    "\001\002\000\006\010\uffda\013\043\001\002\000\004\044" +
    "\034\001\002\000\010\010\uffd9\013\027\015\026\001\002" +
    "\000\004\044\031\001\002\000\010\016\024\043\023\044" +
    "\025\001\002\000\004\010\uffe0\001\002\000\006\010\uffdc" +
    "\013\032\001\002\000\010\016\024\043\023\044\025\001" +
    "\002\000\004\010\uffde\001\002\000\010\010\uffd8\013\036" +
    "\015\035\001\002\000\004\044\040\001\002\000\010\016" +
    "\024\043\023\044\025\001\002\000\004\010\uffdf\001\002" +
    "\000\006\010\uffdb\013\041\001\002\000\010\016\024\043" +
    "\023\044\025\001\002\000\004\010\uffdd\001\002\000\010" +
    "\016\024\043\023\044\025\001\002\000\004\010\uffe1\001" +
    "\002\000\006\006\uffe2\007\016\001\002\000\004\006\uffe3" +
    "\001\002\000\006\042\052\043\051\001\002\000\006\012" +
    "\053\013\054\001\002\000\006\012\ufff1\013\ufff1\001\002" +
    "\000\006\012\ufff0\013\ufff0\001\002\000\004\014\057\001" +
    "\002\000\006\042\056\043\055\001\002\000\006\012\ufff3" +
    "\013\ufff3\001\002\000\006\012\ufff2\013\ufff2\001\002\000" +
    "\022\002\ufff4\025\010\026\013\027\006\031\012\032\004" +
    "\037\007\041\005\001\002\000\004\002\ufffe\001\002\000" +
    "\004\002\001\001\002\000\004\005\063\001\002\000\004" +
    "\043\064\001\002\000\006\006\uffe4\013\070\001\002\000" +
    "\004\006\066\001\002\000\022\002\ufff4\025\010\026\013" +
    "\027\006\031\012\032\004\037\007\041\005\001\002\000" +
    "\004\002\000\001\002\000\004\043\064\001\002\000\004" +
    "\006\uffe5\001\002\000\004\004\073\001\002\000\004\040" +
    "\074\001\002\000\004\011\075\001\002\000\004\042\076" +
    "\001\002\000\004\013\077\001\002\000\004\043\100\001" +
    "\002\000\004\013\101\001\002\000\016\017\107\020\106" +
    "\021\104\022\110\023\102\024\103\001\002\000\004\013" +
    "\uffeb\001\002\000\004\013\uffea\001\002\000\004\013\uffed" +
    "\001\002\000\004\013\111\001\002\000\004\013\uffee\001" +
    "\002\000\004\013\uffef\001\002\000\004\013\uffec\001\002" +
    "\000\010\016\114\043\112\044\115\001\002\000\004\012" +
    "\126\001\002\000\004\012\123\001\002\000\004\044\120" +
    "\001\002\000\006\012\uffe9\015\116\001\002\000\004\044" +
    "\117\001\002\000\004\012\uffe7\001\002\000\006\012\uffe8" +
    "\015\121\001\002\000\004\044\122\001\002\000\004\012" +
    "\uffe6\001\002\000\004\014\124\001\002\000\022\002\ufff4" +
    "\025\010\026\013\027\006\031\012\032\004\037\007\041" +
    "\005\001\002\000\004\002\ufff7\001\002\000\004\014\127" +
    "\001\002\000\022\002\ufff4\025\010\026\013\027\006\031" +
    "\012\032\004\037\007\041\005\001\002\000\004\002\ufff6" +
    "\001\002\000\004\004\132\001\002\000\004\030\133\001" +
    "\002\000\004\011\134\001\002\000\004\043\135\001\002" +
    "\000\004\012\136\001\002\000\004\014\137\001\002\000" +
    "\022\002\ufff4\025\010\026\013\027\006\031\012\032\004" +
    "\037\007\041\005\001\002\000\004\002\ufffd\001\002\000" +
    "\004\043\142\001\002\000\004\013\143\001\002\000\004" +
    "\043\144\001\002\000\004\013\145\001\002\000\004\042" +
    "\146\001\002\000\004\013\147\001\002\000\004\043\150" +
    "\001\002\000\004\013\151\001\002\000\004\043\152\001" +
    "\002\000\004\012\153\001\002\000\004\014\154\001\002" +
    "\000\022\002\ufff4\025\010\026\013\027\006\031\012\032" +
    "\004\037\007\041\005\001\002\000\004\002\ufff5\001\002" +
    "\000\004\004\157\001\002\000\012\033\161\034\162\035" +
    "\160\036\163\001\002\000\004\011\217\001\002\000\004" +
    "\011\210\001\002\000\004\011\203\001\002\000\004\011" +
    "\164\001\002\000\004\042\165\001\002\000\004\013\166" +
    "\001\002\000\004\043\167\001\002\000\004\013\170\001" +
    "\002\000\016\017\107\020\106\021\104\022\110\023\102" +
    "\024\103\001\002\000\004\013\172\001\002\000\010\016" +
    "\114\043\173\044\115\001\002\000\004\012\200\001\002" +
    "\000\004\012\175\001\002\000\004\014\176\001\002\000" +
    "\022\002\ufff4\025\010\026\013\027\006\031\012\032\004" +
    "\037\007\041\005\001\002\000\004\002\ufff9\001\002\000" +
    "\004\014\201\001\002\000\022\002\ufff4\025\010\026\013" +
    "\027\006\031\012\032\004\037\007\041\005\001\002\000" +
    "\004\002\ufff8\001\002\000\004\042\204\001\002\000\004" +
    "\012\205\001\002\000\004\014\206\001\002\000\022\002" +
    "\ufff4\025\010\026\013\027\006\031\012\032\004\037\007" +
    "\041\005\001\002\000\004\002\ufffb\001\002\000\004\042" +
    "\211\001\002\000\004\013\212\001\002\000\004\043\213" +
    "\001\002\000\004\012\214\001\002\000\004\014\215\001" +
    "\002\000\022\002\ufff4\025\010\026\013\027\006\031\012" +
    "\032\004\037\007\041\005\001\002\000\004\002\ufffc\001" +
    "\002\000\004\042\220\001\002\000\004\013\221\001\002" +
    "\000\004\043\222\001\002\000\004\012\223\001\002\000" +
    "\004\014\224\001\002\000\022\002\ufff4\025\010\026\013" +
    "\027\006\031\012\032\004\037\007\041\005\001\002\000" +
    "\004\002\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\223\000\004\002\010\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\016\001\001\000\004" +
    "\006\021\001\001\000\002\001\001\000\004\002\020\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\027\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\032\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\036\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\006\041\001\001\000" +
    "\002\001\001\000\004\006\043\001\001\000\002\001\001" +
    "\000\004\005\045\001\001\000\002\001\001\000\004\010" +
    "\047\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\002\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\064\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\002\066\001\001\000\002\001\001\000\004\004\070\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\104\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\112\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\002\124" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\002" +
    "\127\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\002\137\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\002\154\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\003\170\001\001\000\002" +
    "\001\001\000\004\007\173\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\002\176\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\002\201\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\002\206\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\002\215\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\002\224\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$analisis_sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$analisis_sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$analisis_sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


      
    
    //para el metodo leer archivos
    Stack<String> pila_claves = new Stack<String>();
    Stack<Object> pila_registros = new Stack<Object>();

    //para las tablas de registros de archivos
    public DefaultTableModel modeloTablaArchivo;
    public static HashMap<String,DefaultTableModel> hmTablasArchivos= new HashMap<String,DefaultTableModel>();
    
    //para errores
    public static Stack<String> pila_imprimirErrores = new Stack<String>();
    public static Stack<String> pila_imprimirErroresLexSintArchi = new Stack<String>();

    //para guardar variables y verificar si existe la variable
    public static HashMap<String,Object> alExistenciaDeVariable= new HashMap<String,Object>();

    public int contCuantasClaves=0;
    public int contRegistros=0;

    //para guardar los errores sintacticos
    public static Object [] encabezado={"","",""};
    public static DefaultTableModel tablaerroresSintacticos=new DefaultTableModel(encabezado,0);

    //para verificar si hay error sintactico en archivo datos
    public boolean errorSintacticoArchivo=false;
        
    // ------------------------------busca y devuelve un string con el contenido que tiene un archivo de datos ------------------------------------
    //---------------------------------------------------------------------------------------------------------------------------------------------
    String buscarArchivo(String ruta)
    {
        String bb="";
        String rutaBuscar=ruta.substring(1,ruta.length()-1);
        
        try {
            String aa; 
            FileReader f = new FileReader(rutaBuscar);
            BufferedReader bf = new BufferedReader(f);
            while ((aa = bf.readLine())!=null) {
                bb+=aa+"\n";                
             }
        } catch (Exception e) {
            System.out.println("eror buscar archivo"+e);
            String er="LA RUTA: " + ruta + " NO HA SIDO ENCONTRADA!";
            pila_imprimirErrores.push(er);
        }
        return bb;
    }

    //--------------------------------------------para leer la estructura de un archivo------------------------------------------------------------
    //---------------------------------------------------------------------------------------------------------------------------------------------
    public void leerArchivo(String texto, String idArchivo)
    {
        try {
            Analizador_Lexico_Archivos lexico= new Analizador_Lexico_Archivos(new BufferedReader(new StringReader(texto)));
            analisis_sintactico sintactico = new analisis_sintactico(lexico);
            lexico.errorLexicoArchivo=false;
            sintactico.errorSintacticoArchivo=false;            
            sintactico.parse(); 
            if(sintactico.errorSintacticoArchivo==false && lexico.errorLexicoArchivo==false)
            {
                if(sintactico.verificarSiNumeroRegistrosConcuerdanConClaves(idArchivo,sintactico.contCuantasClaves ,sintactico.contRegistros)==true)
                {
                    if(sintactico.ingresarClavesYRegistrosEnTabla(idArchivo,sintactico.pila_claves,sintactico.pila_registros,sintactico.contCuantasClaves ,sintactico.contRegistros)==true)
                    {
                            sintactico.guardarIDArchivoDatosYContenido(idArchivo,sintactico.pila_claves,sintactico.contCuantasClaves ,sintactico.contRegistros);
                    }
                } 
            }else{
                String er="EL ARCHIVO: " + idArchivo + " CONTIENE ERRORES LEXICOS O SINTACTICOS!";
                pila_imprimirErroresLexSintArchi.push(er);
            }

                       
        } catch (Exception e) {
            System.out.println("error funcion leer archivo"+e.getMessage());
        }
    }
   

    //------------------------------verifica si los registros concuerdan con el numero de claves ----------------------------------------------------
    //---------------------------------------------------------------------------------------------------------------------------------------------
    public boolean verificarSiNumeroRegistrosConcuerdanConClaves(String idArchivo,int numClaves, int numRegistros)
    {   
        boolean ve=true;     
       if(numRegistros%numClaves!=0)
       {
          String aa="ERROR EN EL ARCHIVO: " + idArchivo + " LA CANTIDAD DE DATOS DE UNO A VARIOS REGISTROS ES INCORRECTA";
          pila_imprimirErrores.push(aa);
          ve=false;
       }
       return ve;
    }

    // ------------------------------ concatena la forma de mostrar en consola un archivo de datos--------------------------------------------------
    //---------------------------------------------------------------------------------------------------------------------------------------------
    public void guardarIDArchivoDatosYContenido(String idArchivo, Stack claves,int numClaves, int numRegistros)
    {
       int reg =numRegistros / numClaves;
       Stack<String> pilacla = (Stack<String>)claves.clone(); 
       String cla="Claves= [";
       while(!pilacla.empty())
       {
            cla+=pilacla.pop() + ",";
       }
       cla+="]" + "\n";
       cla+= "Numero de registros= " + reg;
       //contenidoImpriArchivo.put(idArchivo,cla);
       alExistenciaDeVariable.put(idArchivo,cla);
    }

    //------------------------------guarda el contenido de los archivos en modelo de tablas -------------------------------------------------------
    //---------------------------------------------------------------------------------------------------------------------------------------------
    public boolean ingresarClavesYRegistrosEnTabla(String idArchivo, Stack claves, Stack registros, int numClaves, int numRegistros)
    {
       Stack<String> pilacla = (Stack<String>)claves.clone(); 
       Stack<String> pilareg = (Stack<String>)registros.clone();
       
       ArrayList<String> lista = new ArrayList<String>(); //para los registros
       ArrayList<String> lista2 = new ArrayList<String>(); //para las claves
       ArrayList<String> lista3 = new ArrayList<String>(); //para darle vuelta a los registros
       String list=""; //para guardar el .pop de pilareg
       
       String cla="{"; //para concatenar las claves
       String reg=""; //como auxiliar para concatenar claves
       String regis=""; //para concatenar para meterlo de la forma: { {a,b,c} , {d,e,f} , {g,h,i} }
       
       boolean guardomodelotable=true;
       
       int contador=0;
       int cuandoTermina=numRegistros/numClaves;
       int contadorCuandoTermina=0;

       while(!pilacla.empty())
       {
            reg=pilacla.pop();
            lista2.add(reg);
            cla+=reg + ",";
       }
       String a=cla.substring(0,cla.length()-1); 
       cla=a;
       cla+="}";
       
       //para agregar a la 'lista' los registros
       for (int i = 0; i < numRegistros; i++) 
        {    
            contador++;
            if(contador==numClaves)
            {
               list=pilareg.pop();
               lista.add(list);
               contador=0;
               
            }else
            {
               list=pilareg.pop();
               lista.add(list);
            }            
        }
       
       //para darle vuelta y agregar a nueva 'lista3'
       for (int i = lista.size()-numClaves; i >= 0; i-=numClaves) 
        {
            for (int j = i; j < (i+numClaves); j++) 
            {
                lista3.add(lista.get(j));
            }
        }
                     
        JTable prueba=new JTable();        
        Object [] encabezado=new Object[numClaves]; //se crea un array del tamanio del numero de claves
        
        //se llena el encabezado para pasarlo como parametro en el modelo
        for (int i = 0; i < numClaves; i++) 
        {            
            encabezado[i]=i;            
        }
                
        modeloTablaArchivo=new DefaultTableModel(encabezado, 0); //se crea el modelo con el numero de columnas 'encabezado'
        Object [] ingresar= new Object[numClaves]; //para ir agregando las filas al modelo
        
        //para agregar a la tabla el tipo de dato de cada columna
        for (int i = 0; i < numClaves; i++) 
        {
            String temp=lista3.get(i);
            //para saber si es numerico o string
            try {
                Double aux=Double.parseDouble(temp); //si lo coniverte es numero o decimal
                ingresar[i]="numerico";
            } catch (Exception e) {
                ingresar[i]="string";
            }          
        }
        modeloTablaArchivo.addRow(ingresar);
        Arrays.fill(ingresar, null); //me limpia el array
        
        //para agregar a la tabla nombre de las claves
        for (int i = 0; i < numClaves; i++) 
        {
            String temp=lista2.get(i);
            //temp=temp.substring(1,temp.length()-1);//para quitarle las comillas a las claves
            ingresar[i]=temp;         
        }
        modeloTablaArchivo.addRow(ingresar);
        Arrays.fill(ingresar, null); //me limpia el array
        
        //para agregar al modelo
       for (int i = 0; i < numRegistros; i++) //para que no agregue el primer registro que nos dice el tipo de dato
        {    
            contador++;
            if(contador==numClaves) //cada vez que termine un bloque registro 
            {
               ingresar[contador-1]=lista3.get(i);
               modeloTablaArchivo.addRow(ingresar);
               Arrays.fill(ingresar, null);
               contador=0;
               
            }else if(i%numClaves==0) 
            {
               ingresar[contador-1]=lista3.get(i);
            }
            else 
            {
               ingresar[contador-1]=lista3.get(i); 
            }            
        }
       

       //impresion de tabla
//        for (int i = 0; i < modeloTablaArchivo.getRowCount(); i++) 
//        {
//            for (int j = 0; j < modeloTablaArchivo.getColumnCount(); j++) 
//            {
//                System.out.print(modeloTablaArchivo.getValueAt(i, j)+ "  ");
//            }
//            System.out.println("");
//        }
        
        //verificar el tipo de dato de cada registro
        for (int i = 2; i < modeloTablaArchivo.getRowCount(); i++) 
        {
            for (int j = 0; j < modeloTablaArchivo.getColumnCount(); j++) //comienza en 2, ya que la fila 0 es el tipo de dato y fila 1 nombre de clave
            {
                String temp=modeloTablaArchivo.getValueAt(i, j).toString(); //capturamos el valor de una celda de tabla
                
                try { //se trata de convertir a numerico
                    Double aux=Double.parseDouble(temp); //si lo coniverte es numero o decimal
                    if (modeloTablaArchivo.getValueAt(0, j).equals("numerico")) 
                    {                        
                    }
                    else if (modeloTablaArchivo.getValueAt(0, j).equals("string")) 
                    {
                        String er="ERROR EN EL ARCHIVO: " + idArchivo + "  --> EL REGISTRO: " + temp + " NO ES DEL TIPO DE DATO CORRECTO";
                        pila_imprimirErrores.push(er);
                        guardomodelotable=false;
                    }
                
                } catch (Exception e) //cuando el registro es string
                {
                    if (modeloTablaArchivo.getValueAt(0, j).equals("string")) 
                    {                        
                    }
                    else if (modeloTablaArchivo.getValueAt(0, j).equals("numerico")) 
                    {
                        String er="ERROR EN EL ARCHIVO: " + idArchivo + "  --> EL REGISTRO: " + temp + " NO ES DEL TIPO DE DATO CORRECTO";
                        pila_imprimirErrores.push(er);
                        guardomodelotable=false;
                    }                    
                } 
            }
        }  

        if(guardomodelotable==true) //si no hay errores me guarda el modelo de tabla
        {
            hmTablasArchivos.put(idArchivo,modeloTablaArchivo);
        }
        return guardomodelotable;    
    }
    
    
    //Metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {        
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;
        
        Object[] cars = {lexema, fila, columna};
        tablaerroresSintacticos.addRow(cars);
        //String aa="ERROR SINTACTICO: PRINCI " + "Lexema: " + lexema + " Fila: " + fila + " Columna: " + columna + "\n";
        //System.out.println(aa);        
        //System.out.println("\t\tLexema: "+lexema);
        //System.out.println("\t\tFila: "+fila);
        //System.out.println("\t\tColumna: "+columna);
        errorSintacticoArchivo=true;       
                
    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {        
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;
        
        //System.out.println("!!!!!!! Error Sintactico NORMAL!!!!!!! ");
        //System.out.println("\t\tLexema: "+lexema);
        //System.out.println("\t\tFila: "+fila);
        //System.out.println("\t\tColumna: "+columna);
        

    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$analisis_sintactico$actions {



  private final analisis_sintactico parser;

  /** Constructor */
  CUP$analisis_sintactico$actions(analisis_sintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$analisis_sintactico$do_action_part00000000(
    int                        CUP$analisis_sintactico$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintactico$parser,
    java.util.Stack            CUP$analisis_sintactico$stack,
    int                        CUP$analisis_sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$analisis_sintactico$result;

      /* select the action based on the action number */
      switch (CUP$analisis_sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).value;
		RESULT = start_val;
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$analisis_sintactico$parser.done_parsing();
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= claves igual corchabre VALORES_CLAVE corchcierra INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= registros igual corchabre REGISTROS corchcierra INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO ::= imprimir parenabre IMPRICOCAT parencierra puntocoma INICIO 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).value;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INICIO ::= archivo id igual leerarchivo parenabre cadena parencierra puntocoma INICIO 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-7)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-7)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-7)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).value;
		 if(alExistenciaDeVariable.containsKey(a.toString()))
                {
                   String exis="LA VARIABLE " + a.toString() + " YA EXISTE! \n" ;
                   pila_imprimirErrores.push(exis); 
                }else
                {
                String datos=buscarArchivo(b.toString());
                leerArchivo(datos, a.toString()); }              
            
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INICIO ::= numerico id igual sumar parenabre id coma cadena parencierra puntocoma INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-10)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INICIO ::= numerico id igual contar parenabre id parencierra puntocoma INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // INICIO ::= numerico id igual promedio parenabre id coma cadena parencierra puntocoma INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-10)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // INICIO ::= numerico id igual contarsi parenabre id coma cadena coma OPERADORES coma VALOR parencierra puntocoma INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-14)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // INICIO ::= numerico id igual contarsi parenabre id coma cadena coma OPERADORES coma cadena parencierra puntocoma INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-14)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // INICIO ::= cadenareserv id igual obtenersi parenabre id coma cadena coma OPERADORES coma VALOR parencierra puntocoma INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-14)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // INICIO ::= cadenareserv id igual obtenersi parenabre id coma cadena coma OPERADORES coma cadena parencierra puntocoma INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-14)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // INICIO ::= graficar parenabre cadena coma cadena coma id coma cadena coma cadena parencierra puntocoma INICIO 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-13)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // INICIO ::= 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // IMPRICOCAT ::= IMPRICOCAT coma cadena 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("IMPRICOCAT",6, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // IMPRICOCAT ::= IMPRICOCAT coma id 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("IMPRICOCAT",6, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // IMPRICOCAT ::= cadena 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("IMPRICOCAT",6, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // IMPRICOCAT ::= id 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("IMPRICOCAT",6, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // OPERADORES ::= mayor 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("OPERADORES",1, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // OPERADORES ::= menor 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("OPERADORES",1, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // OPERADORES ::= mayorigualque 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("OPERADORES",1, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // OPERADORES ::= menorigualque 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("OPERADORES",1, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // OPERADORES ::= igualigual 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("OPERADORES",1, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // OPERADORES ::= diferenteque 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("OPERADORES",1, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // VALOR ::= enteroposit 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALOR",5, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // VALOR ::= menos enteroposit 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALOR",5, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // VALOR ::= enteroposit punto enteroposit 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALOR",5, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // VALOR ::= menos enteroposit punto enteroposit 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALOR",5, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // VALORES_CLAVE ::= cadena coma VALORES_CLAVE 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).value;
		 contCuantasClaves++; 
                        pila_claves.push(a.toString()); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_CLAVE",2, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // VALORES_CLAVE ::= cadena 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.peek()).value;
		 contCuantasClaves++; 
                        pila_claves.push(a.toString()); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_CLAVE",2, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // REGISTROS ::= llaveabre VALORES_REGISTROS llavecierra REGISTROS 
            {
              Object RESULT =null;
		  
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("REGISTROS",3, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // REGISTROS ::= 
            {
              Object RESULT =null;

              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("REGISTROS",3, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // VALORES_REGISTROS ::= cadena coma VALORES_REGISTROS 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).value;
		 contRegistros++;  
                       pila_registros.push(a.toString()); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // VALORES_REGISTROS ::= enteroposit coma VALORES_REGISTROS 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).value;
		 contRegistros++;
                       pila_registros.push(a.toString());
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // VALORES_REGISTROS ::= menos enteroposit coma VALORES_REGISTROS 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).value;
		 contRegistros++;
                       String ing= a.toString() + b.toString();
                       pila_registros.push(ing); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // VALORES_REGISTROS ::= enteroposit punto enteroposit coma VALORES_REGISTROS 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-4)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).value;
		 contRegistros++;
                       String ing= a.toString() + b.toString() + c.toString();
                       pila_registros.push(ing); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // VALORES_REGISTROS ::= menos enteroposit punto enteroposit coma VALORES_REGISTROS 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-5)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-5)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-4)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-4)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-4)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).value;
		 contRegistros++;
                       String ing= a.toString() + b.toString() + c.toString() + d.toString();
                       pila_registros.push(ing); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // VALORES_REGISTROS ::= enteroposit punto enteroposit 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.peek()).value;
		 contRegistros++;
                       String ing= a.toString() + b.toString() + c.toString();
                       pila_registros.push(ing); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // VALORES_REGISTROS ::= menos enteroposit punto enteroposit 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.peek()).value;
		 contRegistros++;
                       String ing= a.toString() + b.toString() + c.toString() + d.toString();
                       pila_registros.push(ing); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // VALORES_REGISTROS ::= cadena 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.peek()).value;
		 contRegistros++;  
                       pila_registros.push(a.toString()); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // VALORES_REGISTROS ::= enteroposit 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.peek()).value;
		 contRegistros++; 
                       pila_registros.push(a.toString()); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // VALORES_REGISTROS ::= menos enteroposit 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.peek()).value;
		 contRegistros++; 
                       String ing= a.toString() + b.toString();
                       pila_registros.push(ing); 
              CUP$analisis_sintactico$result = parser.getSymbolFactory().newSymbol("VALORES_REGISTROS",4, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$analisis_sintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$analisis_sintactico$do_action(
    int                        CUP$analisis_sintactico$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintactico$parser,
    java.util.Stack            CUP$analisis_sintactico$stack,
    int                        CUP$analisis_sintactico$top)
    throws java.lang.Exception
    {
              return CUP$analisis_sintactico$do_action_part00000000(
                               CUP$analisis_sintactico$act_num,
                               CUP$analisis_sintactico$parser,
                               CUP$analisis_sintactico$stack,
                               CUP$analisis_sintactico$top);
    }
}

}
