
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos_impri {
  /* terminals */
  public static final int cadenareserv = 29;
  public static final int parencierra = 8;
  public static final int cadena = 33;
  public static final int registros = 20;
  public static final int promedio = 27;
  public static final int coma = 9;
  public static final int archivo = 21;
  public static final int imprimir = 23;
  public static final int llaveabre = 5;
  public static final int corchabre = 3;
  public static final int contarsi = 28;
  public static final int sumar = 25;
  public static final int leerarchivo = 22;
  public static final int claves = 19;
  public static final int numerico = 24;
  public static final int menos = 12;
  public static final int menor = 14;
  public static final int punto = 11;
  public static final int parenabre = 7;
  public static final int obtenersi = 30;
  public static final int igual = 2;
  public static final int EOF = 0;
  public static final int id = 32;
  public static final int puntocoma = 10;
  public static final int contar = 26;
  public static final int error = 1;
  public static final int mayorigualque = 15;
  public static final int llavecierra = 6;
  public static final int corchcierra = 4;
  public static final int graficar = 31;
  public static final int menorigualque = 16;
  public static final int diferenteque = 18;
  public static final int igualigual = 17;
  public static final int enteroposit = 34;
  public static final int mayor = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "igual",
  "corchabre",
  "corchcierra",
  "llaveabre",
  "llavecierra",
  "parenabre",
  "parencierra",
  "coma",
  "puntocoma",
  "punto",
  "menos",
  "mayor",
  "menor",
  "mayorigualque",
  "menorigualque",
  "igualigual",
  "diferenteque",
  "claves",
  "registros",
  "archivo",
  "leerarchivo",
  "imprimir",
  "numerico",
  "sumar",
  "contar",
  "promedio",
  "contarsi",
  "cadenareserv",
  "obtenersi",
  "graficar",
  "id",
  "cadena",
  "enteroposit"
  };
}

